# Generated by Django 5.0.6 on 2024-06-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCGPAGE', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductosMYL',
            fields=[
                ('id_myl', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('imagen', models.CharField(max_length=200)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
