# Generated by Django 5.0.6 on 2024-06-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCGPAGE', '0004_rename_productosmyl_productomagic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductosGlobales',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('imagen', models.CharField(max_length=200)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
