# Generated by Django 5.0.6 on 2024-06-25 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TCGPAGE', '0003_productosmagic_productospoke_productosyugi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductosMYL',
            new_name='ProductoMagic',
        ),
        migrations.RenameModel(
            old_name='ProductosYugi',
            new_name='ProductoMYL',
        ),
        migrations.RenameModel(
            old_name='ProductosPoke',
            new_name='ProductoPoke',
        ),
        migrations.RenameModel(
            old_name='ProductosMagic',
            new_name='ProductoYugi',
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
        migrations.RenameField(
            model_name='productomagic',
            old_name='id_myl',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='productomyl',
            old_name='id_yugi',
            new_name='id_myl',
        ),
        migrations.RenameField(
            model_name='productopoke',
            old_name='id_poke',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='productoyugi',
            old_name='id_magic',
            new_name='id',
        ),
    ]
